name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Package Application
        run: zip -r app.zip . -x ".git/*" "node_modules/*"


      - name: Prepare SSH Environment
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Write SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Debug SSH Connection
        run: |
          ssh -vvv -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo Connection Successful"

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "app.zip"
          target: "/home/ubuntu/"
          debug: true

      - name: Deploy Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Update system and install dependencies
            sudo apt-get update
            sudo apt-get install -y nodejs npm unzip
            sudo npm install -g pm2

            # Ensure /var/www directory exists with correct permissions
            sudo mkdir -p /var/www/furnitureshop
            sudo chown -R $USER:$USER /var/www/furnitureshop

            # Unzip application without prompt
            unzip -o ~/app.zip -d /var/www/furnitureshop

            # Change to the application directory
            cd /var/www/furnitureshop

            # Install application dependencies
            npm install

            # Start or restart the application using pm2
            pm2 describe furnitureshop > /dev/null
            if [ $? -eq 0 ]; then
              pm2 restart furnitureshop
            else
              pm2 start app.js --name "furnitureshop"
            fi

